# Generated by Django 5.0.6 on 2024-05-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
    ]
