# Generated by Django 5.0.6 on 2024-05-11 21:19

from django.db import migrations



def populate_role(apps, schemaeditor):
    entries = {
        "developer": "person on the team who works on issues",
        "product_owner": "person on the team who writes issues",
        "scrum_master": "team coach"
        }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()



def populate_team(apps, schemaeditor):
     entries = {
          "Alpha": "Team A",
          "Bravo": "Team B",
          "Charlie": "Team C"
     }
     Team = apps.get_model("accounts", "Team")
     for key, value in entries.items():
         team_obj = Team(name=key, description=value)
         team_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_description_alter_team_description'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_team),
    ]
